// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AcceptandviewnewacpTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void acceptandviewnewacp() {
    driver.get("http://localhost:5173/");
    driver.manage().window().setSize(new Dimension(1175, 634));
    driver.findElement(By.id("login_name")).click();
    driver.findElement(By.id("login_name")).sendKeys("admin");
    driver.findElement(By.id("login_email")).click();
    driver.findElement(By.id("login_email")).click();
    driver.findElement(By.id("login_email")).sendKeys("admin@ua.pt");
    driver.findElement(By.cssSelector(".field:nth-child(3) .input")).click();
    driver.findElement(By.cssSelector(".field:nth-child(3) .input")).sendKeys("admin");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.linkText("Pending requests")).click();
    driver.findElement(By.cssSelector(".border-b")).click();
    driver.findElement(By.cssSelector(".bg-blue-700")).click();
    driver.findElement(By.cssSelector(".border-b:nth-child(3)")).click();
    driver.findElement(By.linkText("Search in area")).click();
    driver.findElement(By.id("default-search")).click();
    driver.findElement(By.id("default-search")).sendKeys("Aveiro");
    driver.findElement(By.cssSelector(".w-36")).click();
    driver.findElement(By.cssSelector(".border-b:nth-child(3)")).click();
    driver.findElement(By.linkText("See All")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
